CRUD_AspNET_CoreMVC/Models/ErrorViewModel.cs
using System;

namespace CRUD_AspNET_CoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD_AspNET_CoreMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRUD_AspNET_CoreMVC.Models;

namespace CRUD_AspNET_CoreMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD_AspNET_CoreMVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using Microsoft.AspNetCore.Mvc;
using Repository;

namespace CRUD_AspNET_CoreMVC.Controllers
{
    public class UsuarioController : Controller
    {
        public IUsuarioDAL UsuarioDAL { get; }

        public UsuarioController(IUsuarioDAL usuarioDAL)
        {
            UsuarioDAL = usuarioDAL;
        }

        public IActionResult Index()
        {
            List<Usuario> listaUsuarios = UsuarioDAL.GetAll().ToList();

            return View(listaUsuarios);
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public JsonResult GetDetails(int? codigo)
        {
            if(codigo == null) { return Json("Inválido."); }

            Usuario usuario = UsuarioDAL.GetUsuario(codigo);

            if(usuario == null) { return Json("Não encontrado."); }

            return Json(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateUsuario([FromBody]Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                if (UsuarioDAL.AddUsuario(usuario))
                    return Json("Sucesso");
                else
                    return Json("Falha");
            }
            else
                return Json("Inválido");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateUsuario([FromBody]Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                if (UsuarioDAL.UpdateUsuario(usuario))
                    return Json("Sucesso");
                else
                    return Json("Falha");
            }
            else
                return Json("Inválido");
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteUsuario(int? codigo)
        {
            if (ModelState.IsValid)
            {
                if (UsuarioDAL.DeleteUsuario(codigo))
                    return Json("Sucesso");
                else
                    return Json("Falha");
            }
            else
                return Json("Inválido");
        }
    }
}

CRUD_AspNET_CoreMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CRUD_AspNET_CoreMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CRUD_AspNET_CoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CRUD_AspNET_CoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD ASP.NET Core MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/usuariost.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CRUD ASP.NET Core MVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuário</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - CRUD ASP.NET Core MVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery.blockUI.js" asp-append-version="true"></script>
        <script src="~/js/bootbox/bootbox.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/usuario.js" asp-append-version="false"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>        
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CRUD_AspNET_CoreMVC/Views/Usuario/Index.cshtml
@model IEnumerable<Entity.Usuario>

    @{
    ViewData["Title"] = "Index";
    }

    @Html.AntiForgeryToken()

    <h2>Usuários</h2>

    <div style="overflow-y: auto; max-height: 250px">
        <table class="table" id="tbUsuarios">
            <thead>
                <tr>
                    <th>
                        Código
                    </th>
                    <th>
                        Nome do Usuário
                    </th>
                    <th>
                        Data de Nascimento
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataNascimento)                        
                    </td>
                    <td>
                        <input type="button" class="btn btn-default btnEdit" name="@item.Codigo" value="Editar" />
                        <input type="button" class="btn btn-default btnDetail" name="@item.Codigo" value="Detalhes" />
                        <input type="button" class="btn btn-default btnDelete" name="@item.Codigo" value="Deletar" />
                    </td>
                </tr>
}
            </tbody>
        </table>
    </div>
    <p>
        <label type="button" class="btn btn-primary" data-toggle="modal" data-target="#divCreate">Adicionar Usuário</label>
    </p>
    <div>
        <partial name="_PartialCreate" />
    </div>
    <div>
        <partial name="_PartialDetail" />
    </div>
    <div>
        <partial name="_PartialEdit" />
    </div>

CRUD_AspNET_CoreMVC/Views/Usuario/_PartialCreate.cshtml
<div class="modal fade" id="divCreate" role="dialog">
    <div class="modal-dialog" role="document" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="float: left">Novo Usuário</h4>
                <button class="btn btn-default" data-dismiss="modal" style="width: 35px; float: right;">x</button>
            </div>
            <div class="modal-body">
                <p>Nome: <input class="form-control txtNome" style="width: 100%;" /></p>
                <p>Data de Nascimento: <input type="date" min="1900-01-01" max="@DateTime.Now.ToString("d")" placeholder="0000-00-00" class="form-control txtDataNascimento" style="width: 100%;" /></p>
                <p style="text-align: right;"><label id="btnSalvarUsuario" type="button" class="btn btn-primary">Salvar</label></p>
            </div>
        </div>
    </div>    
</div>

CRUD_AspNET_CoreMVC/Views/Usuario/_PartialDetail.cshtml
<div class="modal fade" id="divDetail" role="dialog">
    <div class="modal-dialog" role="document" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="float: left">Usuário Selecionado</h4>
                <button class="btn btn-default" data-dismiss="modal" style="width: 35px; float: right;">x</button>
            </div>
            <div class="modal-body">
                <p>Código: <input class="form-control txtCodigo" style="width: 100%;" disabled="disabled"/></p>
                <p>Nome: <input class="form-control txtNome" style="width: 100%;" disabled="disabled"/></p>
                <p>Data de Nascimento: <input type="date" class="form-control txtDataNascimento" style="width: 100%;" disabled="disabled"/></p>
            </div>
        </div>
    </div>
</div>

CRUD_AspNET_CoreMVC/Views/Usuario/_PartialEdit.cshtml
<div class="modal fade" id="divEdit" role="dialog">
    <div class="modal-dialog" role="document" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="float: left">Usuário Selecionado</h4>
                <button class="btn btn-default" data-dismiss="modal" style="width: 35px; float: right;">x</button>
            </div>
            <div class="modal-body">
                <p>Código: <input class="form-control txtCodigo" style="width: 100%;" disabled="disabled" /></p>
                <p>Nome: <input class="form-control txtNome" style="width: 100%;" /></p>
                <p>Data de Nascimento: <input type="date" class="form-control txtDataNascimento" min="1900-01-01" max="@DateTime.Now.ToString("d")" placeholder="0000-00-00" style="width: 100%;" /></p>
                <p style="text-align: right;"><label id="btnSalvarUsuario" type="button" class="btn btn-primary">Salvar</label></p>
            </div>
        </div>
    </div>
</div>